version: '3.0'
services:
  payment_app:
    build: .
    ports:
      - 3003:3003
    hostname: payment_app
    env_file: .env
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      payment_app_db:
        condition: service_healthy
    # networks:
    #   - payment-network

  payment_app_db:
    image: cassandra:latest
    ports:
      - '9042:9042'
    hostname: payment_app_db
    volumes:
      - ./db:/var/lib/cassandra
    healthcheck:
      test: ['CMD-SHELL', '[ $$(nodetool statusgossip) = running ]']
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
  #     networks:
  #       - payment-network

  payment_app_queue:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 5s
      timeout: 3s
      retries: 5
#     networks:
#       - payment-network

# networks:
#   payment-network:
#     driver: bridge
