services:
  ticket_app_db:
    image: postgres:latest
    restart: always
    volumes:
      - "./ticket-app/db:/var/lib/postgresql/data"
      - "./ticket-app/migrations:/docker-entrypoint-initdb.d/"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER_TICKET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TICKET}
      POSTGRES_DB: ${DB_NAME_TICKET}