version: '3.0'
services:
  ticket_app_db:
    image: postgres:latest
    restart: always
    volumes:
      - "../ticket-app/db:/var/lib/postgresql/data"
      - "../ticket-app/migrations:/docker-entrypoint-initdb.d/"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER_TICKET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TICKET}
      POSTGRES_DB: ${DB_NAME_TICKET}
    networks:
      - app-network
  ticket_app:
    image: ticket-app:latest
    restart: always
    volumes:
      - ../ticket-app/src:/usr/src/app/src
    ports:
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - ticket_app_db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge