version: "3.8"
services:
  client_app:
    build: .
    ports:
      - 3333:3333
    hostname: tubes-client-app
    env_file: .env
    volumes:
      - ./:/usr/app
    depends_on:
      - client_app_db
  client_app_db:
    image: postgres:alpine
    ports:
      - 5436:5432
    hostname: tubes-client-app-db
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
